FROM python:3.12-slim

RUN apt-get update && apt-get install -y python3-distutils

WORKDIR /app
COPY backend/ /app/
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "watcher/ws_server.py"]