version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  candles-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    restart: unless-stopped